- src/Pages/LandingPage.jsx
Fixes #9
When we press the "Learn More" button, it will now redirect to the section which was requested in the issue.
> [FIX]: Modified the learn more button #9

- backend/models.py
Added unique in model for email and phone number fields
> Email and Phone Number should be unique closes #13

- src/Pages/Booking.jsx
- src/Pages/LandingPage.jsx
- src/main.jsx
Fixes #8
Description:- So as the issue suggest, I implemented the /book-nurse route and the Home tracker is fixed in that page.
By the results of searchquery, the results will be displayed there.
Screenshots:-
> [Feature]:Added the /book-nurse route

- src/Pages/Blogs.jsx
- src/main.jsx
Fixes #18
Description:- So as was told, I added the dynamic routes for all the blogs, and after clicking on a particular blog, a different page will open which will show the details of the blogs.
Screenshots:-
So when the content of the blog will be big then the ui will be like this:-
> [Feature]:Added the blogs function where clicking on the blog opens up the new blog page

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature.yml
This PR fixes the issue #32 , kindly review it and merge.
> feat: create issue templates

- src/components/Footer/Footer.jsx
Successfully Updated the Social Media Handles as Provided.
> Updated Linkedin Handle and Contact us Handle #31

- CODE_OF_CONDUCT.md
#51 
Community
This change was necessary to establish clear guidelines for community behavior, ensuring a welcoming and inclusive environment for all contributors. By implementing a Code of Conduct, we aim to uphold mutual respect, professionalism, and collaboration, fostering a healthier and more productive community for everyone involved.
> Add: Code of Conduct for Better Collaboration

- src/components/Header/Header.jsx
**Fixes** #33
**Description:-** So, as I mentioned in the issue, I would give the hovering effect in navbar elements. So I did, on hovering over the nav tags, they would scale up to some extent.
**How it is tested:-** I tested it multiple times in my local system.
> [Feat]: Fixed the navbar elements hovering effect

- package.json
- src/Pages/LoginPage.jsx
- src/Pages/SignupPage.jsx
> [FIX] Fixed Confirm password masking not working 

- public/assets/XMarkIcon.svg
- src/components/Header/Header.jsx
- src/components/Header/MenuOverlay.jsx
I have added the functionality of the hamburger menu in mobile screens, enhancing the navigation experience on smaller devices.
Changes Made:
1. Added the MenuOverlay component  component which renders a menu with a list of navigation links.
2. Called the MenuOverlay component in the Header component, passing the array of objects containing the info about the navigation links to the MenuOverlay component. 
3. Included an X mark icon instead of the hamburger icon whenever the menu is open. 
Screenshots:
Please let me know if any improvements/changes are required.
> Added the hamburger menu functionality for mobile screens.

- src/Pages/Booking.jsx
- tailwind.config.js
> Fixes: Search text not visible #101

- src/Pages/AboutPage.jsx
- src/Pages/CareersPage.jsx
- src/components/Footer/Footer.jsx
Closes #94 
The UI of the about and career section is made responsive for every screen sizes.
fixes and closes issue #94 
@Harshil-Jani please add labels like gssoc and level2 to the pr also.
> Fix/issue #94 About and Career section made responsive

- src/components/Header/Header.jsx
- src/index.css
issue #98 
The elements in the navbar made responsive for screen above 768px as per the issue #117 and dark mode toggle button updated.
closes issue #117 , please add the label like gssoc and level2 to the pr also.
> fixed issue #117 Updated the UI of the navbar -breaking at 768px of screen size- resolved

- README.md
I have added information about:
Tools to be installed
Installation steps
Contribution steps.
Issue #5
Thank You
> Added Installation and Contribution steps in README.md

- src/index.css
Header Stikcy Fixed
we added featured where header is sticky for user freindly header
- [ x] Bug fix
- [x ] Feature enhancement
https://github.com/Nactore-Org/Nacto-Care/assets/109230049/ebbd50f3-966a-46cc-9f77-ef4df4d4486b
> header-sticky-fixed

- package.json
- src/main.jsx
Fixes #109 
added Lenis for smooth scroll
> fix: added Lenis for smooth scroll

- src/Pages/LandingPage.jsx
- src/components/Header/Header.jsx
#110 
Changed the look of landing page and navbar buttons in dark mode for  better accessibility.
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/f0b892dc-8a89-423e-99d4-854f95375886
no additional info required here.
> changed box shadows for navbar buttons and landing page buttons

- src/Pages/Licensing.jsx
- src/Pages/PrivacyPolicy.jsx
- src/Pages/TermsAndConditions.jsx
- src/components/BackBtn/BackBtn.jsx
- src/main.jsx
"None"
The Privacy Policy , Terms & condition, licensing page made responsive for every screen sizes.
closes issue #119 , please label the pr with gssoc level2.
> fixes issue-#119 Policy, Terms & condition, licensing page made responsive

- src/components/Header/Header.jsx
- src/index.css
Issue #132 
Added a sun-moon theme toggle switch to the header component, replacing the existing theme switcher. I have now replaced the existing theme switch with a sun-moon theme toggle switch along with animations.
Please review my PR and let me know if any changes are required.
> Replaced the theme toggle with a sun-moon theme toggle switch.

- src/components/Header/Header.jsx
- src/components/Header/MenuOverlay.jsx
#148 
Changed the location of the theme button to the hamburger button menu.
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/ed7cc08b-df9b-47aa-8cf0-0a0ae8786ac4
> Relocated the theme button in menu on mobile

- src/Pages/ContactPage.jsx
- src/ScrollToTopButton.jsx
- src/components/Header/Header.jsx
- src/components/Header/MenuOverlay.jsx
- src/index.css
- src/main.jsx
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
Hey , I have solved #99  and #147 
[Please include a brief description of the changes or features added]
I have made the texts visible on dark mode wherever they are not visible.
I have added scroll to top button.
- [x ] Bug fix
Here the texts were not visible.
Before:
After:
Before:
After:
Added scroll to top:
https://github.com/Nactore-Org/Nacto-Care/assets/102676949/9e8a29cf-a344-4765-a51d-fa91720cf1e9
> Changes Done

- .github/workloads/auto-comment-on-pr-merge.yml
Closes #116 
I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.
> Added the feature to auto comment on pr merged 

- package.json
- src/components/Layout.jsx
Closes #88.
An AI chatbot on Nacto Care website can provide 24/7 customer support, offer healthcare information.
The chatbot can ask preliminary questions to understand the user’s needs and direct them to the appropriate healthcare professional.
The chatbot can provide users with information about different types of care, insurance coverage, and other services.
https://github.com/Nactore-Org/Nacto-Care/assets/132576984/49aeb9a9-2e91-4936-86a9-3891edb4b1cc
> Added AI Chatbot

- package.json
- src/Pages/LandingPage.jsx
Issue #133 
1. Installed the `react-scroll` npm package.
2. Modified the "Learn More" button to use ScrollLink from react-scroll for smooth scrolling.
Please review my PR and let me know if any changes are required. Thank you!
> Fixed 'Learn More' Scroll Issue Using react-scroll Components

- src/Pages/Blogs.jsx
Issue #134 
1. Added the avatar of the author with the author's name in the left section. 
2. Made a few changed to the styles of the title and the date.
Please review my PR and provide feedback. I will be happy to work on the suggestions to improve the blog page further.
> Redesigned the blog page.

- .github/workflows/greetings.yml
Fixes #159 
rewrote the greeting
> fix: greeting CI Activity

- index.html
- src/components/Header/Header.jsx
This PR fixes #163 
[Please include a brief description of the changes or features added]
I have added icons on the navbar
- [ x] Feature enhancement
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
> Added icons on the navbar

- src/Pages/Faq.jsx
- src/Pages/Faqpage.jsx
- src/components/FAQ/Faqdata.js
- src/components/Footer/Footer.jsx
- src/main.jsx
- src/styles/Faq.css
Resolved issue #146 
@Harshil-Jani can you please check and let me know if there are any changes?
> Added FAQ page

- src/Pages/LoginPage.jsx
- src/Pages/SignupPage.jsx
fixes: #173 
[Please include a brief description of the changes or features added]
forget password not visible in dark mode
> improved ui of signIn and singUp pages

- src/Pages/ContactPage.jsx
I added a hovering animation on the send message button just same like the other buttons on the website to make same theme .
closes : #180 
Before :
https://github.com/Nactore-Org/Nacto-Care/assets/118350936/ca0ab649-74d3-4957-9eca-725553420d13
After ; 
https://github.com/Nactore-Org/Nacto-Care/assets/118350936/aa29ac8d-e1e0-4074-bcd8-aedad3384ab3
> Animation not showing in contact page send message button fixed #180

- src/components/Header/MenuOverlay.jsx
- src/index.css
I added the hamburger animation to the amburger menu so it opens up with animation
closes : #179 
https://github.com/Nactore-Org/Nacto-Care/assets/118350936/df514cf9-dc1b-44a4-b208-135cac01cb3a
- [] I have commented my code, particularly in hard-to-understand areas.
> hamburger animation #179

- src/Pages/BlogPage.jsx
- src/index.css
I added the hovering animation on card when user hovers on the card the card will be scale out with a white box shadow .
closes : #186
https://github.com/Nactore-Org/Nacto-Care/assets/118350936/bde0367d-84fe-42b6-98bc-328ca9df1f59
> Hovering Animation on card #186

- src/components/Footer/Footer.jsx
Static year in footer section
Using js function now every year it will get sync to corresponding year automatically small yet effective issue resolved
> edited code for dynamic year

- src/components/Form/Form.jsx
Issue #182 
Updated the 'Find your Home care Taker' form in the landing page for dark theme using appropriate background color and text color. 
Please review my PR and provide feedback. I'll be happy to work on any required changes.
> 'Find your Home Care Taker' form fixed in dark theme

- src/components/Header/Header.jsx
Issue #184 
Implemented a change that automatically scrolls to the top of the page whenever a new route is navigated to using the navbar links. This improves the navigation experience by ensuring that the user is always taken to the top of the new page, rather than being left at the same vertical scroll position as they were on the previous page.
[recording-2024-05-30-18-43-54.webm](https://github.com/Nactore-Org/Nacto-Care/assets/127531721/5c699046-3b16-42b1-955b-0d007d9ce66f)
Please review my PR and provide feedback. I'll be happy to work on any required changes.
> Implemented scroll to top on navigation link click

- src/components/Footer/Footer.jsx
resolves #169 
Redirected social media links to a new tab. This improves user experience and convenience.
- [x ] Feature enhancement
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
> Redirecting social media links to a new tab

- src/Pages/FeedbackForm.jsx
- src/components/Footer/Footer.jsx
- src/components/Layout.jsx
- src/main.jsx
Fixes #154 
The following changes have been made in the project:
- Added a "Help Us Improve!" sticky button on all pages of the website and included it in the footer.
- Implemented a dedicated feedback form on the website.
https://github.com/Nactore-Org/Nacto-Care/assets/153659573/db2022c8-ce36-474f-9f31-8015edb4c3ea
> FIXED #154 : Added a Feedback Form

- package.json
- src/components/Footer/Footer.jsx
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
[Please include a brief description of the changes or features added]
- [x ] Feature enhancement
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
> Adding social media icons to the footer

- src/Pages/BlogPage.jsx
- src/Pages/Blogs.jsx
- src/components/SingleBlog.jsx
#207 
Following features/changes have been made:
- Made SingleBlog component which will get the blog prop so now its more optimized.
- Added tags in blogs javascript object for categorizing.
- Added Top, Trending, and Latest Tabs.
- Made the tabs responsive.
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/a74a41af-1cad-4913-a277-b04861217f89
Also what about the content is it going to be stored in the javascript object too?
> added tabs in blogs section

- src/Pages/BlogPage.jsx
- src/index.css
- src/styles/BrandCenter.css
closes: #219
added related blogs of nacto care
##Screenshots/videos (if applicable)
- [x ] I have commented my code, particularly in hard-to-understand areas.
> Added blogs in blogs section

- src/ScrollToTopButton.jsx
closes #244 
Hey @Harshil-Jani I have re-designed the scroll to top button using react styled-components
https://github.com/Nactore-Org/Nacto-Care/assets/101971980/b8b7af33-7809-407c-a358-9fd57f2aeea2
Please take a look at review it, Thank You!!
> Re-designed Scroll-to-Top button

- src/components/Form/Form.jsx
#240
Added Validation for date and time so now date lower than current date cannot be entered and if its current date than time needs to be greater than current time.
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/c12b2b2a-ad7c-4e10-af56-889bf448c7d7
> added validation for date and time fields for medical need form

- src/Pages/LandingPage.jsx
#239 fixed
Landing page image hover & tilt effect fixed
https://github.com/Nactore-Org/Nacto-Care/assets/125277258/becf15cf-011a-481f-a0ab-c54ed0921c8a
> Landing page image hover & tilt effect fixed
